pre-requisits:
	@go install github.com/bacalhau-project/lilypad@latest
	@go install github.com/ipfs-shipyard/git-remote-ipld/cmd/git-remote-ipld@latest

install:
	@npm install && npm install -g node-ts
